# Generated by Django 3.1 on 2020-08-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('title_fi', models.CharField(max_length=200)),
                ('title_sv', models.CharField(default='Enter title', max_length=200)),
                ('title_en', models.CharField(default='Enter title', max_length=200)),
                ('content_fi', models.TextField(blank=True)),
                ('content_sv', models.TextField(default='Enter content')),
                ('content_en', models.TextField(default='Enter content')),
            ],
        ),
    ]
