# Generated by Django 3.1 on 2020-08-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
