# Generated by Django 3.1 on 2020-08-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuts', '0002_shortcut_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='title_en',
            field=models.CharField(default='Enter title', max_length=500),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='title_fi',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='title_sv',
            field=models.CharField(default='Enter title', max_length=500),
        ),
    ]
