# Generated by Django 3.1 on 2020-08-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='title_fi',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=models.TextField(default='Enter content'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_fi',
            field=models.TextField(default='Enter content'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_sv',
            field=models.TextField(default='Enter content'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(default='Enter title', max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='title_sv',
            field=models.CharField(default='Enter title', max_length=200),
        ),
    ]
