# Generated by Django 3.1 on 2020-08-05 10:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200804_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content_fi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
