# Generated by Django 3.1 on 2020-08-07 08:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200805_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content_sv',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
