# Generated by Django 3.1 on 2020-08-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='placement_id',
            field=models.CharField(default='abc123', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shortcut',
            name='placement_id',
            field=models.CharField(default='cfg321', max_length=64),
            preserve_default=False,
        ),
    ]
