# Copyright 2020 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT

# Use non-root version of nginx
FROM nginxinc/nginx-unprivileged
COPY nginx.conf /etc/nginx/conf.d/
EXPOSE 8080