# Copyright 2024 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT

apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: nginx-revproxy-cms-devel
  annotations:
    description: "Research.fi CMS Nginx reverse proxy for devel"
    iconClass: icon-nginx
  labels:
    app: nginx-revproxy-cms-devel
    template: nginx-revproxy-cms-devel
objects:

# Service
- apiVersion: v1
  kind: Service
  metadata:
    name: nginx-revproxy-cms-devel
    labels:
      app: nginx-revproxy-cms-devel
    annotations:
      description: Nginx reverse proxy for CMS content (devel)
  spec:
    ports:
      - name: nginx
        port: 8080
        targetPort: 8080
    selector:
      app: nginx-revproxy-cms-devel

# Route
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: nginx-revproxy-cms-devel
    labels:
      app: nginx-revproxy-cms-devel
  spec:
    host: cms-nginx-devel-researchfi.2.rahtiapp.fi
    to:
      kind: Service
      name: nginx-revproxy-cms-devel
      weight: 100
    port:
      targetPort: nginx
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None

# ImageStream
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: nginx-revproxy-cms-devel
    labels:
      app: nginx-revproxy-cms-devel

# BuildConfig using Docker build strategy
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: nginx-revproxy-cms-devel
    labels:
      app: nginx-revproxy-cms-devel
  spec:
    source:
      git:
        uri: https://github.com/CSCfi/research-fi-cms.git
        ref: devel
      contextDir: nginx/devel/rahti2
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: nginx-unprivileged:latest
        dockerfilePath: Dockerfile
    output:
      to:
        kind: ImageStreamTag
        name: nginx-revproxy-cms-devel:latest
    successfulBuildsHistoryLimit: 2 
    failedBuildsHistoryLimit: 2

# Deployment config
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx-revproxy-cms-devel
    labels:
      app: nginx-revproxy-cms-devel
  spec:
    selector:
      matchLabels:
        app: nginx-revproxy-cms-devel
    template:
      metadata:
        labels:
          app: nginx-revproxy-cms-devel
      spec:
        containers:
          - name: nginx-revproxy-cms-devel
            image: image-registry.openshift-image-registry.svc:5000/researchfi-devel/nginx-revproxy-cms-devel:latest
            imagePullPolicy: Always
            ports:
              - containerPort: 8080
                protocol: TCP
    replicas: 1
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - nginx-revproxy-cms-devel
        from:
          kind: ImageStreamTag
          name: nginx-revproxy-cms-devel:latest
    strategy:
      type: RollingUpdate