FROM ubuntu:22.04
ENV PYTHONUNBUFFERED 1

# Install Postgres to enable command 'psql'
RUN apt update && apt install -y postgresql-client python3 python3-pip

RUN mkdir /code
WORKDIR /code
COPY django/requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
