FROM python:3.9
ENV PYTHONUNBUFFERED 1

# Install Postgres to enable command 'psql'
RUN apt update && apt install -y postgresql postgresql-contrib

RUN mkdir /code
WORKDIR /code
COPY django/requirements.txt /code/
RUN pip install -r requirements.txt
