# Generated by Django 3.1 on 2020-08-26 10:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('title_fi', models.CharField(max_length=200)),
                ('title_sv', models.CharField(default='Enter title', max_length=200)),
                ('title_en', models.CharField(default='Enter title', max_length=200)),
                ('content_fi', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('content_sv', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('placement_id', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('title_fi', models.CharField(max_length=500)),
                ('title_sv', models.CharField(default='Enter title', max_length=500)),
                ('title_en', models.CharField(default='Enter title', max_length=500)),
                ('content_fi', models.TextField(blank=True)),
                ('content_sv', models.TextField(default='Enter content')),
                ('content_en', models.TextField(default='Enter content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('link', models.URLField(blank=True, max_length=500)),
                ('placement_id', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
