# Generated by Django 3.1 on 2020-11-27 09:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('placement_id', models.IntegerField()),
                ('title_fi', models.CharField(default='Enter title', max_length=500)),
                ('title_sv', models.CharField(default='Enter title', max_length=500)),
                ('title_en', models.CharField(default='Enter title', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('title_fi', models.CharField(max_length=200)),
                ('title_sv', models.CharField(default='Enter title', max_length=200)),
                ('title_en', models.CharField(default='Enter title', max_length=200)),
                ('content_fi', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('content_sv', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('page_id', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('name_fi', models.CharField(default='Enter sector name', max_length=500)),
                ('name_sv', models.CharField(default='Enter sector name', max_length=500)),
                ('name_en', models.CharField(default='Enter sector name', max_length=500)),
                ('subtitle_fi', models.CharField(blank=True, max_length=500)),
                ('subtitle_sv', models.CharField(blank=True, max_length=500)),
                ('subtitle_en', models.CharField(blank=True, max_length=500)),
                ('placement_id', models.PositiveIntegerField(db_index=True)),
                ('iframe_fi', models.CharField(blank=True, max_length=500)),
                ('iframe_en', models.CharField(blank=True, max_length=500)),
                ('iframe_sv', models.CharField(blank=True, max_length=500)),
                ('description_fi', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('description_sv', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('icon', models.CharField(default='Add icon code', max_length=500)),
            ],
            options={
                'ordering': ['placement_id'],
            },
        ),
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('link', models.CharField(choices=[('/', 'Etusivu'), ('/results/publications', 'Julkaisut'), ('/results/fundings', 'Hankkeet'), ('/results/infrastructures', 'Infrastruktuurit'), ('/results/organizations', 'Organisaatiot'), ('/news', 'Uutiset'), ('/science-innovation-policy/research-innovation-system', 'Tutkimus- ja innovaatiojärjestelmä'), ('/science-innovation-policy/science-research-figures', 'Lukuja tieteestä ja tutkimuksesta'), ('javascript:void(0)', 'Script'), ('/service-info', 'Tietoa palvelusta'), ('/sitemap', 'Sivukartta'), ('/accessibility', 'Saavutettavuus'), ('/privacy', 'Tietosuoja')], default='/', max_length=500)),
                ('placement_id', models.IntegerField()),
                ('title_fi', models.CharField(max_length=500)),
                ('title_sv', models.CharField(default='Enter title', max_length=500)),
                ('title_en', models.CharField(default='Enter title', max_length=500)),
                ('content_fi', models.TextField(blank=True)),
                ('content_sv', models.TextField(default='Enter content')),
                ('content_en', models.TextField(default='Enter content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_alt_fi', models.CharField(blank=True, default='', max_length=500)),
                ('image_alt_sv', models.CharField(blank=True, default='', max_length=500)),
                ('image_alt_en', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['placement_id'],
            },
        ),
        migrations.CreateModel(
            name='SingleFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_id', models.PositiveIntegerField(db_index=True)),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('title_fi', models.CharField(max_length=500)),
                ('title_sv', models.CharField(default='Enter title', max_length=500)),
                ('title_en', models.CharField(default='Enter title', max_length=500)),
                ('description_fi', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('description_sv', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/figures/')),
                ('iframe_fi', models.CharField(blank=True, max_length=500)),
                ('iframe_en', models.CharField(blank=True, max_length=500)),
                ('iframe_sv', models.CharField(blank=True, max_length=500)),
                ('source_fi', models.CharField(blank=True, max_length=500)),
                ('source_en', models.CharField(blank=True, max_length=500)),
                ('source_sv', models.CharField(blank=True, max_length=500)),
                ('info_fi', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('info_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('info_sv', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('roadmap', models.BooleanField(default=False)),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contentapp.figure')),
            ],
            options={
                'ordering': ['figure', 'placement_id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('name_fi', models.CharField(default='Enter organization name', max_length=500)),
                ('name_sv', models.CharField(default='Enter organization name', max_length=500)),
                ('name_en', models.CharField(default='Enter organization name', max_length=500)),
                ('placement_id', models.PositiveIntegerField(db_index=True)),
                ('link', models.CharField(default='Enter link target', max_length=500)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='contentapp.sector')),
            ],
            options={
                'ordering': ['sector', 'placement_id'],
            },
        ),
    ]
