# Generated by Django 3.1 on 2020-10-28 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('title_fi', models.CharField(max_length=500)),
                ('title_sv', models.CharField(default='Enter title', max_length=500)),
                ('title_en', models.CharField(default='Enter title', max_length=500)),
                ('description_fi', models.TextField(default='Enter content')),
                ('description_en', models.TextField(default='Enter content')),
                ('description_sv', models.TextField(default='Enter content')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/figures/')),
                ('iframe_fi', models.CharField(max_length=500)),
                ('iframe_en', models.CharField(max_length=500)),
                ('iframe_sv', models.CharField(max_length=500)),
                ('linkId', models.CharField(blank=True, max_length=4)),
                ('placement_id', models.CharField(blank=True, max_length=4)),
                ('source_fi', models.CharField(max_length=500)),
                ('source_en', models.CharField(max_length=500)),
                ('source_sv', models.CharField(max_length=500)),
                ('info_fi', models.TextField(default='Enter content')),
                ('info_en', models.TextField(default='Enter content')),
                ('info_sv', models.TextField(default='Enter content')),
                ('roadmap', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('title_fi', models.CharField(max_length=500)),
                ('title_sv', models.CharField(default='Enter title', max_length=500)),
                ('title_en', models.CharField(default='Enter title', max_length=500)),
                ('content_fi', models.TextField(blank=True)),
                ('content_sv', models.TextField(default='Enter content')),
                ('content_en', models.TextField(default='Enter content')),
                ('figures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.singlefigure')),
            ],
        ),
    ]
