# Generated by Django 3.1 on 2020-12-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['page_id']},
        ),
    ]
