# Generated by Django 3.1 on 2021-01-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0002_auto_20201215_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLinksParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_id', models.PositiveIntegerField(db_index=True)),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('title_fi', models.CharField(default='Enter title', max_length=500)),
                ('title_sv', models.CharField(default='Enter title', max_length=500)),
                ('title_en', models.CharField(default='Enter title', max_length=500)),
            ],
            options={
                'ordering': ['placement_id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_id', models.PositiveIntegerField(db_index=True)),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('label_fi', models.CharField(default='Enter link label', max_length=500)),
                ('label_sv', models.CharField(default='Enter link label', max_length=500)),
                ('label_en', models.CharField(default='Enter link label', max_length=500)),
                ('content_fi', models.CharField(default='Enter content', max_length=1000)),
                ('content_sv', models.CharField(default='Enter content', max_length=1000)),
                ('content_en', models.CharField(default='Enter content', max_length=1000)),
                ('url', models.URLField(help_text='Enter link target', max_length=500)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='contentapp.externallinksparent')),
            ],
            options={
                'ordering': ['parent', 'placement_id'],
            },
        ),
    ]
