# Generated by Django 3.1 on 2020-10-28 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0002_figure_singlefigure'),
    ]

    operations = [
        migrations.CreateModel(
            name='FigureParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('title_fi', models.CharField(max_length=500)),
                ('title_sv', models.CharField(default='Enter title', max_length=500)),
                ('title_en', models.CharField(default='Enter title', max_length=500)),
                ('content_fi', models.TextField(blank=True)),
                ('content_sv', models.TextField(default='Enter content')),
                ('content_en', models.TextField(default='Enter content')),
            ],
        ),
        migrations.RenameField(
            model_name='figure',
            old_name='content_en',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='figure',
            old_name='content_sv',
            new_name='description_fi',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='content_fi',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='figures',
        ),
        migrations.AddField(
            model_name='figure',
            name='description_sv',
            field=models.TextField(default='Enter content'),
        ),
        migrations.AddField(
            model_name='figure',
            name='iframe_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='figure',
            name='iframe_fi',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='figure',
            name='iframe_sv',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='figure',
            name='info_en',
            field=models.TextField(default='Enter content'),
        ),
        migrations.AddField(
            model_name='figure',
            name='info_fi',
            field=models.TextField(default='Enter content'),
        ),
        migrations.AddField(
            model_name='figure',
            name='info_sv',
            field=models.TextField(default='Enter content'),
        ),
        migrations.AddField(
            model_name='figure',
            name='link_id',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='figure',
            name='parent',
            field=models.CharField(default='Enter parent number', max_length=2),
        ),
        migrations.AddField(
            model_name='figure',
            name='placement_id',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='figure',
            name='roadmap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='figure',
            name='source_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='figure',
            name='source_fi',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='figure',
            name='source_sv',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='figure',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/figures/'),
        ),
        migrations.DeleteModel(
            name='SingleFigure',
        ),
        migrations.AddField(
            model_name='figureparent',
            name='figures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.figure'),
        ),
    ]
