# Generated by Django 3.1 on 2020-10-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0003_auto_20201028_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='figureparent',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='figureparent',
            name='content_fi',
        ),
        migrations.RemoveField(
            model_name='figureparent',
            name='content_sv',
        ),
        migrations.RemoveField(
            model_name='figureparent',
            name='figures',
        ),
        migrations.AddField(
            model_name='figureparent',
            name='placement_id',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='figure',
            name='parent',
            field=models.CharField(choices=[('1', '1, Tutkimuksen rahoitus'), ('2', '2, Tutkimuksen henkilövoimavarat'), ('3', '3, Julkaisutoiminta ja tieteellinen vaikuttavuus')], default='1', max_length=1),
        ),
    ]
