# Generated by Django 3.1 on 2021-01-26 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0003_externallink_externallinksparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlefigure',
            name='visual_file',
            field=models.FileField(blank=True, null=True, upload_to='visuals/'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contentapp.externallinksparent'),
        ),
    ]
