# Generated by Django 3.1 on 2021-01-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0004_auto_20210126_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlefigure',
            old_name='visual_file',
            new_name='visual_file_en',
        ),
        migrations.AddField(
            model_name='singlefigure',
            name='visual_file_fi',
            field=models.FileField(blank=True, null=True, upload_to='visuals/'),
        ),
        migrations.AddField(
            model_name='singlefigure',
            name='visual_file_sv',
            field=models.FileField(blank=True, null=True, upload_to='visuals/'),
        ),
    ]
