# Generated by Django 3.1 on 2020-10-28 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0004_auto_20201028_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.figureparent'),
        ),
    ]
