# Generated by Django 3.1 on 2021-02-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contentapp", "0005_auto_20210126_1147"),
    ]

    operations = [
        migrations.RenameField(
            model_name="externallink",
            old_name="url",
            new_name="url_fi",
        ),
        migrations.AddField(
            model_name="externallink",
            name="url_en",
            field=models.URLField(
                help_text="Enter link target", max_length=500, null=True
            ),
        ),
        migrations.AddField(
            model_name="externallink",
            name="url_sv",
            field=models.URLField(
                help_text="Enter link target", max_length=500, null=True
            ),
        ),
    ]
