# Generated by Django 3.1 on 2020-10-28 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0005_auto_20201028_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='figureparent',
            name='figures',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contentapp.figure'),
        ),
        migrations.AlterField(
            model_name='figure',
            name='parent',
            field=models.CharField(choices=[('1', '1, Tutkimuksen rahoitus'), ('2', '2, Tutkimuksen henkilövoimavarat'), ('3', '3, Julkaisutoiminta ja tieteellinen vaikuttavuus')], default='1', max_length=1),
        ),
    ]
