# Generated by Django 3.1 on 2021-03-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0006_auto_20210216_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlefigure',
            name='update_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
