# Generated by Django 3.1 on 2021-03-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0007_singlefigure_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlefigure',
            name='update_date',
        ),
        migrations.AddField(
            model_name='singlefigure',
            name='visual_update_date_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='singlefigure',
            name='visual_update_date_fi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='singlefigure',
            name='visual_update_date_sv',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
