# Generated by Django 3.1 on 2020-10-28 13:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0008_album_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleFigure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('title_fi', models.CharField(max_length=500)),
                ('title_sv', models.CharField(default='Enter title', max_length=500)),
                ('title_en', models.CharField(default='Enter title', max_length=500)),
                ('description_fi', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('description_sv', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/figures/')),
                ('iframe_fi', models.CharField(blank=True, max_length=500)),
                ('iframe_en', models.CharField(blank=True, max_length=500)),
                ('iframe_sv', models.CharField(blank=True, max_length=500)),
                ('link_id', models.CharField(blank=True, max_length=4)),
                ('placement_id', models.IntegerField()),
                ('source_fi', models.CharField(blank=True, max_length=500)),
                ('source_en', models.CharField(blank=True, max_length=500)),
                ('source_sv', models.CharField(blank=True, max_length=500)),
                ('info_fi', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('info_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('info_sv', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('roadmap', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['placement_id'],
            },
        ),
        migrations.RemoveField(
            model_name='figure',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='description_fi',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='description_sv',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='iframe_en',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='iframe_fi',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='iframe_sv',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='info_en',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='info_fi',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='info_sv',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='link_id',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='roadmap',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='source_en',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='source_fi',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='source_sv',
        ),
        migrations.RemoveField(
            model_name='figure',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='figure',
            name='placement_id',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='figure',
            name='title_fi',
            field=models.CharField(default='Enter title', max_length=500),
        ),
        migrations.DeleteModel(
            name='FigureParent',
        ),
        migrations.AddField(
            model_name='singlefigure',
            name='figure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contentapp.figure'),
        ),
        migrations.AddField(
            model_name='singlefigure',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentapp.figure'),
        ),
        migrations.AlterUniqueTogether(
            name='singlefigure',
            unique_together={('figure', 'placement_id')},
        ),
    ]
