# Generated by Django 3.1 on 2021-09-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0008_auto_20210316_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='iframe_en',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='iframe_fi',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='iframe_sv',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
