# Generated by Django 3.1 on 2020-10-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0009_auto_20201028_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlefigure',
            name='parent',
        ),
    ]
