# Generated by Django 3.1 on 2020-10-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0010_remove_singlefigure_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='placement_id',
            field=models.IntegerField(),
        ),
    ]
