# Generated by Django 3.1 on 2020-10-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0011_auto_20201029_0852'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
