# Generated by Django 3.1 on 2020-10-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0012_auto_20201029_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='placement_id',
            field=models.IntegerField(),
        ),
    ]
