# Generated by Django 3.1 on 2020-10-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0013_auto_20201029_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortcut',
            options={'ordering': ['placement_id']},
        ),
    ]
