# Generated by Django 3.1 on 2020-10-29 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0016_auto_20201029_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortcut',
            name='description',
        ),
    ]
