# Generated by Django 3.1 on 2020-11-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0022_singlefigure_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlefigure',
            options={'ordering': ('placement_id',)},
        ),
    ]
