# Generated by Django 3.1 on 2020-11-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0024_auto_20201117_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlefigure',
            options={'ordering': ['placement_id']},
        ),
    ]
