# Generated by Django 3.1 on 2020-11-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0025_auto_20201117_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlefigure',
            name='order',
        ),
    ]
