# Generated by Django 3.1 on 2020-11-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0027_auto_20201117_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefigure',
            name='placement_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
