# Generated by Django 3.1 on 2020-11-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0029_auto_20201117_1436'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='singlefigure',
            unique_together=set(),
        ),
    ]
