# Generated by Django 3.1 on 2020-11-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0030_auto_20201117_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='image_alt_en',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='shortcut',
            name='image_alt_fi',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='shortcut',
            name='image_alt_sv',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
