# Generated by Django 3.1 on 2020-11-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0031_auto_20201120_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='image_alt_fi',
            field=models.CharField(default='', max_length=500),
        ),
    ]
