# Generated by Django 3.1 on 2020-11-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0033_auto_20201120_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='link',
            field=models.CharField(choices=[('/', 'Etusivu'), ('/results/publications', 'Julkaisut'), ('/results/fundings', 'Hankkeet'), ('/results/infrastructures', 'Infrastruktuurit'), ('/results/organizations', 'Organisaatiot'), ('/news', 'Uutiset'), ('/science-innovation-policy/research-innovation-system', 'Tutkimus- ja innovaatiojärjestelmä'), ('/science-innovation-policy/science-research-figures', 'Lukuja tieteestä ja tutkimuksesta')], default='/', max_length=500),
        ),
    ]
