# Generated by Django 3.1 on 2020-11-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0037_remove_singlefigure_link_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='placement_id',
            new_name='page_id',
        ),
        migrations.AlterField(
            model_name='singlefigure',
            name='placement_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
