# Generated by Django 3.1 on 2020-11-25 07:57

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0038_auto_20201124_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('name_fi', models.CharField(default='Enter sector name', max_length=500)),
                ('name_sv', models.CharField(default='Enter sector name', max_length=500)),
                ('name_en', models.CharField(default='Enter sector name', max_length=500)),
                ('subtitle_fi', models.CharField(blank=True, max_length=500)),
                ('subtitle_sv', models.CharField(blank=True, max_length=500)),
                ('subtitle_en', models.CharField(blank=True, max_length=500)),
                ('placement_id', models.PositiveIntegerField(db_index=True)),
                ('iframe_fi', models.CharField(blank=True, max_length=500)),
                ('iframe_en', models.CharField(blank=True, max_length=500)),
                ('iframe_sv', models.CharField(blank=True, max_length=500)),
                ('description_fi', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('description_sv', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fi', 'Suomi'), ('sv', 'Sverige'), ('en', 'English')], default='fi', max_length=2)),
                ('name_fi', models.CharField(default='Enter organization name', max_length=500)),
                ('name_sv', models.CharField(default='Enter organization name', max_length=500)),
                ('name_en', models.CharField(default='Enter organization name', max_length=500)),
                ('placement_id', models.PositiveIntegerField(db_index=True)),
                ('link', models.CharField(default='Enter link target', max_length=500)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='contentapp.sector')),
            ],
            options={
                'ordering': ['placement_id'],
            },
        ),
    ]
