# Generated by Django 3.1 on 2020-11-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0039_organization_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['sector', 'placement_id']},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['placement_id']},
        ),
        migrations.AddField(
            model_name='sector',
            name='icon',
            field=models.CharField(default='Add icon code', max_length=500),
        ),
    ]
