# Generated by Django 3.1 on 2020-11-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0040_auto_20201125_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='description',
        ),
    ]
