# Generated by Django 3.1 on 2020-11-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0041_remove_page_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlefigure',
            options={'ordering': ['figure', 'placement_id']},
        ),
    ]
