# Generated by Django 3.1 on 2020-11-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentapp', '0043_auto_20201125_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefigure',
            name='placement_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
