# Copyright 2020 Ministry of Education and Culture, Finland
#
# :author: CSC - IT Center for Science Ltd., Espoo Finland servicedesk@csc.fi
# :license: MIT

apiVersion: v1
kind: Template
metadata:
  name: cms-django
  labels:
    app: cms-django-app
    template: cms-django
objects:

# Service
- apiVersion: v1
  kind: Service
  metadata:
    name: cms-django
    labels:
      app: cms-django-app
    annotations:
      description: Django application for CMS
  spec:
    ports:
      - name: cms-django
        port: 8080
        targetPort: 8080
    selector:
      depcfg: cms-django

# ImageStream for devel
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: cms-django
    labels:
      app: cms-django-app

# BuildConfig using source to image (s2i) strategy
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: cms-django
    labels:
      app: cms-django-app
  spec:
    source:
      git:
        uri: https://github.com/CSCfi/research-fi-cms.git
        ref: devel
      contextDir: django
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: docker-registry.default.svc:5000/researchfi/python-36-centos7
        env:
          - name: ENABLE_PIPENV
            value: "true"
          - name: APP_MODULE
            value: "cms.wsgi:application"
          - name: DISABLE_SETUP_PY_PROCESSING
            value: "true"
    output:
      to:
        kind: ImageStreamTag
        name: cms-django:latest
    successfulBuildsHistoryLimit: 4 
    failedBuildsHistoryLimit: 4

# Deployment config
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: cms-django
    labels:
     app: cms-django-app
  spec:
    selector:
      app: cms-django-app
      depcfg: cms-django
    template:
      metadata:
        labels:
          app: cms-django-app
          depcfg: cms-django
      spec:
        containers:
          - name: cms-django
            image: researchfi/cms-django
            imagePullPolicy: Always
            ports:
              - containerPort: 8001
                protocol: TCP
            env:
              - name: DJANGO_ENV_DEBUG
                valueFrom:
                  secretKeyRef:
                    name: cms-django-secret
                    key: django_env_debug
              - name: DJANGO_ENV_SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: cms-django-secret
                    key: django_env_secret_key
              - name: DJANGO_ENV_DATABASE_HOST
                valueFrom:
                  secretKeyRef:
                    name: cms-django-secret
                    key: django_env_database_host
              - name: DJANGO_ENV_DATABASE_PORT
                valueFrom:
                  secretKeyRef:
                    name: cms-django-secret
                    key: django_env_database_port
              - name: DJANGO_ENV_DATABASE_NAME
                valueFrom:
                  secretKeyRef:
                    name: cms-django-secret
                    key: django_env_database_name
              - name: DJANGO_ENV_DATABASE_USER
                valueFrom:
                  secretKeyRef:
                    name: cms-django-secret
                    key: django_env_database_user
              - name: DJANGO_ENV_DATABASE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cms-django-secret
                    key: django_env_database_password
              - name: DJANGO_ENV_MEDIA_URL
                valueFrom:
                  secretKeyRef:
                    name: cms-django-secret
                    key: django_env_media_url
              - name: DJANGO_ENV_STATIC_URL
                valueFrom:
                  secretKeyRef:
                    name: cms-django-secret
                    key: django_env_static_url
              - name: DJANGO_ENV_BACKUP_HTTP_AUTH_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: cms-django-secret
                    key: django_env_backup_http_auth_username
              - name: DJANGO_ENV_BACKUP_HTTP_AUTH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cms-django-secret
                    key: django_env_backup_http_auth_password
            volumeMounts:
              - mountPath: /cmsvolume
                name: cmsvolume
        volumes:
          - name: cmsvolume
            persistentVolumeClaim:
              claimName: cms-volume
    replicas: 1
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - cms-django
        from:
          kind: ImageStreamTag
          name: cms-django:latest
    strategy:
      type: Rolling
